### ISSUE TITLE
order of commands in `[workflow.commands]` (workflows.toml) is not ordered right

### ISSUE THREAD

**Issue by TadaHrd** [TadaHrd/cargo-workflows#1]
```toml
[default]

[default.commands] # This table
clippy = [ "cargo", "clippy" ]
build = [ "cargo", "build", "--release" ]
run = [ "cargo", "run", "--release" ]
```

It gets ordered randomly, since it uses a `HashMap`
